= Bazy danych

== Kod

Przede wszystkim `CustomerVerifier.cs`, który jako serwis aplikacyjny wykorzystuje `VerificationRepository` do połączenia z bazą danych.

W tym projekcie wykorzystujemy ORM (EntityFramework) i własny interfejs IVerificationRepository, który jest używany przez logikę.

Encją zapisywaną w bazie danych będzie `VerifiedPerson`.

W przeciwieństwie do wersji Javowej, migracje bazodanowe wykonywane są na podstawie kodu. Jest w Entity Framework wbudowany mechanizm migracji, jednak na potrzeby tego przykładu nie było potrzeby go użyć.

== Notatki

W przypadku testów integracyjnych z bazą danych trzeba tę bazę danych w jakiś sposób uruchomić. Z jednej strony chcielibyśmy, żeby nie trwało to zbyt długo (uruchomienie bazy, zasilanie jej danymi, interakcja), z drugiej chcielibyśmy żeby testy jak najbardziej odzwierciedlały system produkcyjny. Oczywiście też chcemy pełnej automatyzacji uruchamiania tej bazy.

Potencjalne rozwiązania: Zaślepka, w pamięci, embedded, kontener

=== Zaślepka [01]

==== Klasy

`_01_CustomerVerifierMocksDatabaseTests.cs` - na slajdach zmienione tak, żeby się zmieściło na 1 slajdzie

==== Notatki

* Mocki weryfikują efekty uboczne
* By upewnić się, że się coś po prostu zadziało
* Czy doszło do zapisu do bazy danych
* Zalety
** Natychmiastowe działanie
* Problemy
** Brak testowania integracji
** Dużo kodu ustawiającego stan początkowy

=== Bazy danych uruchamiane w pamięci [02]

==== Klasy

`_02_InMemoryVerificationRepository.cs` - jest to abstrakcja nad zwykłą mapę symulującą bazę danych.

==== Notatki

* Ręcznie zaimplementowana kolekcja
** Ekstremalnie szybkie testy
** Do rozważenia dla głównej części domeny / uruchomienia deweloperskiego
** Brak interakcji z IO
* Symulujące faktyczne bazy
** Symulują dialekty
** H2, HSQLDB, Apache Derby

=== Bazy danych embedded [03]

==== Klasy / Pliki

Klasa `_03_CustomerVerifierWithEmbeddedTests.cs` zawiera testy logiki naszej aplikacji połączonej z osadzoną bazą danych SqLite. W oryginale Javowym była to baza H2. Na potrzeby tego przykładu SQLite jest skonfigurowany tak, żeby działał wyłącznie w pamięci, bez zapisywania danych na dysku.

==== Notatki

* Może zapisywać dane w plikach
** Przy współbieżnym i natężonym użyciu mogą się pojawiać problemy
* Może instalować prawdziwą bazę danych na dysku
* Przykłady
** H2, HSQLDB, Apache Derby, RavenDB, MongoDB, SQLite

=== Bazy danych w kontenerze [04]

==== Klasy / Pliki

Klasa `_04_CustomerVerifierWithContainersTests.cs` zawiera testy zawiera testy logiki naszej aplikacji, połączonej z bazą danych PostgreSQL. Najpierw uruchomiona zostanie baza w kontenerze, a następnie łączymy logikę aplikacji z tą bazą danych.

==== Notatki

* Baza uruchamiana dla danego testu / danej grupy testów w kontenerze
* Dość szybkie w momencie scache’owania obrazu bazy
** Jeszcze szybciej jeśli reużywamy kontenerów
* Przykłady natywnego wsparcia w testach
** Testcontainers, dotnet-testcontainers
* Łatwe do ręcznego zaimplementowania
** Uruchom kontener, uruchom testy wobec kontenera, ubij kontener

https://blog.jooq.org/tag/integration-testing/[Wywiad] z twórcą Testcontainers

> W 2015, przed tym jak rozpocząłem projekt Testcontainers, mieliśmy problemy z paroma funkcjonalnościami MySQL, które nie miały swoich odpowiedników w H2. Dochodziliśmy do wniosku, że być może będziemy musieli ograniczyć funkcjonalności bazy do tego, co pozwala nam H2. Wyszło nam, że jest pewna nisza na rynku do rozwiązania typu H2, które w rzeczywistości jest fasadą na Dockerową bazę danych uruchamianą w kontenerze.