= 01 Testy jednostkowe

Tematy omawiane w tej części:

* Czemu testy są niezbędne
* Czemu testy są opłacalne
* Jakie zasady powinny spełniać dobre testy
* Jak unikać `false passes`:
   - przykład - zestaw testów zawiera test na przypadek negatywny: `CustomerVerifierTest.ShouldFailSimpleVerification`, ale nie zawiera testów weryfikujących pozytywną weryfikację, przez co testy nie wychwytują, że kod produkcyjny zwraca domyślną wartość i brakuje implementacji logiki biznesowej
   - przykład - test `SimpleVerificationTest.ShouldFailSimpleVerificationFalsePass`. Test weryfikuje nie to co trzeba (jakieś pole na obiekcie, zamiast zwracanej wartości), przez co przechodzi, mimo że właściwa implementacja nie została dodana.
* Rodzaje testów
* Struktura testów
  - zobacz np. `NationalIdentificationNumberVerificationTest`
* Konwencje nazewnicze
  - zobacz: `NationalIdentificationNumberVerificationTest`
* Używanie konstruktorów
  - pozwala to między innymi na używanie Test Doubles, zobacz: `TestVerificationService`
* Radzenie sobie z metodami statycznymi:
  - zobacz setup pól klasy testowej w `CustomerVerifierTest`
* Asercje i frameworki do asercji
  - zobacz `AgeVerificationTest`
* Wzorzec AssertObject
 - zobacz `LoanOrderServiceTest`

**DISCLAIMER**

* Kod jest czysto demonstracyjny i nie stanowi wzorcowego kodu projektowego - zamiast na jak
najlepiej napisanym kodzie produkcyjnym koncentrujemy się na przykładach, które pozwalają pokazać
wiele sposobów pracy z testami; często celowo dodajemy "produkcyjny" kod, który nie jest poprawnie 
zaprojektowany po to, żeby pokazać jak sobie z nim radzić i mimo wszystko być w stanie go przetestować
oraz przykłady złych testów, których radzimy unikać.
* Nie polecamy pisania komentarzy po polsku w projektach - tutaj robimy to ponieważ jest to wyłącznie kod szkoleniowy.


