version: '3'

services:
  postgres:
    image: postgres:15.4
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    expose:
      - "5672"
    ports:
      - 5672:5672